### ISSUE TITLE
Moment breaks when using handlebars-helpers

### ISSUE THREAD

**Issue by bradtaylorsf** [helpers/helper-date#1]
In the latest version of 1.0.0 on line 16 in index.js, options.hash is referenced, however hash is a property of pattern.

I was able to fix it by replacing options.hash with pattern. I will create a PR to fix. 

`var opts = Object.assign({}, this, defaults, options, options.hash);`

should be 

`var opts = Object.assign({}, this, defaults, options, pattern);`

**Comment by JSandmark** [comment]
Thank you, I have spent several hours trying to figure this out. Please accept the pull request dear creators!

**Comment by JSandmark** [comment]
@bradtaylorsf can you use lang-parameter with your fix?
` {{moment myDate lang="se"}}`
I cannot pass the lang as it is not set in the helper-date, it defaults to en. I noticed the other issue reported but that does not seem to help me. Any suggestions?

**Comment by JSandmark** [comment]
Any other comments on this issue? This must affect everyone that uses handlebars-helpers (https://github.com/helpers/handlebars-helpers) with a confusing compile error which ends up in this issue. To manually change the source on production like @bradtaylorsf suggested is not really the best solution. Is there anything I can do to assist with the pull request that is not passing checks?
