### ISSUE TITLE
Locale is not passing correctly

### ISSUE THREAD

**Issue by ronenteva** [helpers/helper-date#3]
I was able to fix this by changing

    // set the language to use
    moment.locale(opts.lang);
To:

    // set the language to use
    moment.locale(opts.language);

**Comment by ronenteva** [comment]
Fixed by commit #4

**Comment by jonschlinkert** [comment]
`opts.language` is a property that you would set on your own context, correct? Why would we change that in the helper? fwiw, it's more likely to collide with another variable if we use `language`, and I'd need to do a major.

**Comment by doowb** [comment]
Closing due to age with no response.
