### ISSUE TITLE
Re-introduced bug -- moment breaks

### ISSUE THREAD

**Issue by ylambda** [helpers/helper-date#7]
#1 is back after this line changed.

https://github.com/helpers/helper-date/commit/eb6f9a4dd43d63327a93169d65078acb3e36b2e0#commitcomment-24576918

Adding the pattern object back fixes this.

**Comment by jonschlinkert** [comment]
Closing based on [this comment](https://github.com/helpers/helper-date/commit/eb6f9a4dd43d63327a93169d65078acb3e36b2e0#commitcomment-24578074) since we have insufficient information to reproduce the bug or determine what bug is specifically happening.
